### ISSUE TITLE
painc runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by ll8814081** [sparrc/go-ping#47]
slice bounds out of range  happen when i run ipv4  , i guess the root cause is ipv4Payload method

```go
func (p *Pinger) processPacket(recv *packet) error {
	var bytes []byte
	var proto int
	if p.ipv4 {
		if p.network == "ip" {
			bytes = ipv4Payload(recv)   // this method should change recv.nbytes when process ipv4Header
		} else {
			bytes = recv.bytes
		}
		proto = protocolICMP
	} else {
		bytes = recv.bytes
		proto = protocolIPv6ICMP
	}

	var m *icmp.Message
	var err error
       // if no change recv.nbytes, the bytes will slice bounds out of range
	if m, err = icmp.ParseMessage(proto, bytes[:recv.nbytes]); err != nil {
		return fmt.Errorf("Error parsing icmp message")
	}
}

func ipv4Payload(recv *packet) []byte {
	b := recv.bytes
	if len(b) < ipv4.HeaderLen {
		return b
	}
	hdrlen := int(b[0]&0x0f) << 2
	recv.nbytes -= hdrlen  // this is need
	return b[hdrlen:]
}
```

**Comment by g0rbe** [comment]
Hi!

The bug is still available for me.

My simple code:
```
package main

import (
    "github.com/sparrc/go-ping"
)

func main() {
    pinger, err := ping.NewPinger("www.google.com")
    if err != nil {
            panic(err)
    }
    pinger.Count = 3
    pinger.SetPrivileged(true)
    pinger.Run()
}
```

The error message:
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/sparrc/go-ping.(*Pinger).processPacket(0xc000084680, 0xc00007c8d0, 0x4, 0x3)
	/home/g0rbe/go/src/github.com/sparrc/go-ping/ping.go:460 +0x828
github.com/sparrc/go-ping.(*Pinger).run(0xc000084680)
	/home/g0rbe/go/src/github.com/sparrc/go-ping/ping.go:331 +0x500
github.com/sparrc/go-ping.(*Pinger).Run(...)
	/home/g0rbe/go/src/github.com/sparrc/go-ping/ping.go:278
main.main()

```

(Fresh download, executed as root, running on Arch)
